### ISSUE TITLE
regex/substring match in `.findFirst` methods and similar?

### ISSUE THREAD

**Issue by gderosa** [daveenguyen/atomacos#10]
Hi, I have code like this:

```python
my_menu.AXChildren[0].findFirst(AXTitle='Preferences\u2026')
```

which works fine but relies on exact string match (with an Unicode hellipsis character, which tomorrow may be replaced with three dots or mothing at all).

It would be great to be able to match by regex or substring and/or in a case insensitive manner etc.

Because what I want is just clicking "Preferences"  :)

I know I can probably `findAll()` and then iteratively match, but perhaps there's a better way?

Thanks!

**Comment by daveenguyen** [comment]
IIRC * can be used as wildcard. so
`AXTitle="Preferences*"` should work

https://github.com/daveenguyen/atomacos/blob/master/tests/test_atomacos.py#L136

**Comment by gderosa** [comment]
Excellent, thank you!
